---
title: "Code"
output: 
  html_document:
    toc: true
    toc_float: true
---

<link rel="stylesheet" href="styles.css" type="text/css">

## Test 

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

Look at this 

```{r}
library(ggplot2)
library(dplyr)
library(leaflet)
```


Defining random stuff
```{r,}
g1 <- cbind.data.frame(group = "Group1", value =  3 + rnorm(1000,sd = 4))
g2 <- cbind.data.frame(group = "Group2", value = -2 + rnorm(1000,sd = 2))

data <- rbind.data.frame(g1,g2)
data$y <- runif(1000)
```


Graphing 
```{r}
ggplot(data, aes(y,value,fill = group)) + 
  geom_bin2d(bins = 50, color = "black") + 
  theme_bw() + 
  theme(legend.position = "NULL")
```

## Distance Measures 
get all adresses in Odense from DAWA as .csv
```{r}
test <- read.csv(file = "http://dawa.aws.dk/adresser?postnr=5000&format=csv",encoding = "UTF-8")

#Keep My adresses an another random one  
N <- test %>% 
  filter(grepl("Finlandgade",vejnavn) & husnr == 9 & etage == 6 & dør == "4" | 
           grepl("Kløvervænget",vejnavn) & husnr == 10 & etage == 7 & dør == "701")
```
graph the adresses 
```{r}
leaflet(N) %>%
  addTiles() %>%
  addCircleMarkers(~wgs84koordinat_længde,~wgs84koordinat_bredde,popup = ~vejnavn, label = ~vejnavn)
```







